-- MISSING:
-- Core Vim/Neovim groups
-- NormalNC, NormalSB (alternate “Normal” for inactive splits/status bars)
-- CursorIM, TermCursor, TermCursorNC (cursor highlight variants)
-- WinBar, WinBarNC (top-of-window status lines in recent Neovim)
-- ModeMsg, MoreMsg, Substitute, Ignore, Whitespace
-- MsgArea, MsgSeparator

-- Additional TreeSitter captures
-- @punctuation.special (e.g. backticks in Markdown, special characters)
-- @text.title, @text.reference, @text.environment, @text.environment.name,
--     @text.uri
-- @text.math, @text.note, @text.warning, @text.danger
-- @lsp.typemod.* captures (e.g. @lsp.typemod.readonly,
--     @lsp.typemod.defaultLibrary)

-- Plugin-specific groups
-- WhichKey plugin highlights (WhichKey, WhichKeyDesc, WhichKeyGroup, etc.)
-- NvimTree or NeoTree highlights (for file explorer plugins)
-- Notify plugin (notification popups)
-- Hop/Flash plugins (motion guides)
-- IlluminatedWord (word under cursor highlight)
-- Fidget or LspProgress (LSP progress indicators)
-- Trouble or SymbolsOutline groups

local p = require 'core/palette'
local colors = p

local black = p.gradient[1] -- TODO: blend
local muted = p.gradient[2]
local soft = p.gradient[3] -- TODO; 5 chars?
local clear = p.gradient[4]
local white = p.gradient[5]

local default = p.colors[1] -- TODO: main
local fg = p.fg

local R = '#ff0000'

local groups = {
	Character = { fg = p.colors[7] },
	Comment = { fg = clear, italic = true },
	Constant = { fg = p.colors[7] },
	Normal = { fg = fg, bg = nil },
	NormalFloat = { fg = white, bg = muted },
	Number = { fg = p.colors[7] },
	String = { fg = p.colors[7] },
	----------------------------------------------------------------------------
	Boolean = { fg = R },
	Float = { fg = colors.orange },
	FloatBorder = { fg = white },
	Operator = { fg = default },
	Keyword = { fg = colors.cyan },
	Keywords = { fg = colors.cyan },
	Identifier = { fg = colors.cyan },
	Function = { fg = colors.yellow },
	Statement = { fg = default },
	Conditional = { fg = colors.rose },
	Repeat = { fg = colors.rose },
	Label = { fg = colors.cyan },
	Exception = { fg = default },
	PreProc = { fg = colors.yellow },
	Include = { fg = default },
	Define = { fg = default },
	Title = { fg = colors.cyan },
	Macro = { fg = default },
	PreCondit = { fg = colors.cyan },
	Type = { fg = colors.cyan },
	StorageClass = { fg = colors.rose },
	Structure = { fg = colors.yellow },
	TypeDef = { fg = colors.yellow },
	Special = { fg = colors.green, italic = true },
	SpecialComment = { fg = clear, italic = true },
	Error = { fg = colors.magenta },
	Todo = { fg = default, bold = true, italic = true },
	Underlined = { fg = colors.cyan, underline = true },

	Cursor = { reverse = true },
	CursorLineNr = { fg = white, bold = true },

	SignColumn = { bg = nil },

	Conceal = { fg = colors.gradient[2] },
	CursorColumn = { bg = colors.gradient[2] },
	CursorLine = { bg = colors.gradient[2] },
	ColorColumn = { bg = colors.gradient[2] },

	StatusLine = { fg = white, bg = black },
	StatusLineNC = { fg = colors.gradient[2] },
	StatusLineTerm = { fg = white, bg = black },
	StatusLineTermNC = { fg = colors.gradient[2] },

	Directory = { fg = colors.cyan },
	DiffAdd = { fg = muted, bg = colors.green },
	DiffChange = { fg = colors.orange },
	DiffDelete = { fg = colors.red },
	DiffText = { fg = colors.gradient[2] },

	ErrorMsg = { fg = colors.rose },
	VertSplit = { fg = black },
	WinSeparator = { fg = colors.gradient[3] },
	Folded = { fg = colors.gradient[2] },
	FoldColumn = {},
	Search = { fg = black, bg = colors.orange },
	IncSearch = { fg = colors.orange, bg = colors.gradient[2] },
	LineNr = { fg = colors.gradient[2] },
	MatchParen = { fg = fg, underline = true },
	NonText = { fg = colors.gradient[2] },
	Pmenu = { fg = white, bg = black },
	PmenuSel = { fg = white, bg = colors.gradient[3] },
	PmenuSbar = { bg = muted },
	PmenuThumb = { bg = colors.gradient[3] },

	Question = { fg = colors.red },
	QuickFixLine = { fg = black, bg = colors.yellow },
	SpecialKey = { fg = colors.gradient[2] },

	SpellBad = { fg = colors.rose, underline = true },
	SpellCap = { fg = colors.yellow },
	SpellLocal = { fg = colors.yellow },
	SpellRare = { fg = colors.yellow },

	TabLine = { fg = colors.gradient[2] },
	TabLineSel = { fg = white },
	TabLineFill = { bg = muted },
	Terminal = { fg = white, bg = black },
	Visual = { bg = colors.gradient[3] },
	VisualNOS = { fg = colors.gradient[3] },
	WarningMsg = { fg = colors.yellow },
	WildMenu = { fg = black, bg = white },

	EndOfBuffer = { fg = black },

	-- Notify
	NotifyInfoIcon = { fg = colors.green },
	NotifyInfoTitle = { fg = colors.green },
	NotifyInfoBorder = { fg = '#2C453F' },
	NotifyErrorIcon = { fg = colors.red },
	NotifyErrorTitle = { fg = colors.red },
	NotifyErrorBorder = { fg = '#DD6E6B' },
	NotifyWarnIcon = { fg = colors.orange },
	NotifyWarnTitle = { fg = colors.orange },
	NotifyWarnBorder = { fg = '#785637' },
	NotifyBackground = { fg = '#ff0000', bg = '#ff0000' },

	-- TreeSitter
	['@error'] = { fg = colors.magenta },
	['@punctuation.delimiter'] = { fg = fg },
	['@punctuation.bracket'] = { fg = fg },
	['@markup.list'] = { fg = colors.cyan },

	['@constant'] = { fg = default },
	['@constant.builtin'] = { fg = default },
	['@markup.link.label.symbol'] = { fg = default },

	['@constant.macro'] = { fg = colors.cyan },
	['@string.regexp'] = { fg = colors.red },
	['@string'] = { fg = colors.yellow },
	['@string.escape'] = { fg = colors.cyan },
	['@string.special.symbol'] = { fg = default },
	['@character'] = { fg = colors.green },
	['@number'] = { fg = default },
	['@boolean'] = { fg = default },
	['@number.float'] = { fg = colors.green },
	['@annotation'] = { fg = colors.yellow },
	['@attribute'] = { fg = colors.cyan },
	['@module'] = { fg = colors.orange },

	['@function.builtin'] = { fg = colors.cyan },
	['@function'] = { fg = colors.green },
	['@function.macro'] = { fg = colors.green },
	['@variable.parameter'] = { fg = colors.orange },
	['@variable.parameter.reference'] = { fg = colors.orange },
	['@function.method'] = { fg = colors.green },
	['@variable.member'] = { fg = colors.yellow },
	['@property'] = { fg = colors.blue },
	['@constructor'] = { fg = colors.cyan },

	['@keyword.conditional'] = { fg = colors.magenta },
	['@keyword.repeat'] = { fg = colors.magenta },
	['@label'] = { fg = colors.cyan },

	['@keyword'] = { fg = colors.magenta },
	['@keyword.function'] = { fg = colors.cyan },
	['@keyword.function.ruby'] = { fg = colors.magenta },
	['@keyword.operator'] = { fg = colors.magenta },
	['@operator'] = { fg = colors.magenta },
	['@keyword.exception'] = { fg = colors.red },
	['@type'] = { fg = colors.azure },
	['@type.builtin'] = { fg = colors.cyan, italic = true },
	['@type.qualifier'] = { fg = colors.magenta },
	['@structure'] = { fg = colors.red },
	['@keyword.include'] = { fg = colors.magenta },

	['@variable'] = { fg = fg },
	['@variable.builtin'] = { fg = colors.red },

	['@markup'] = { fg = colors.orange },
	['@markup.strong'] = { fg = colors.orange, bold = true },
	['@markup.emphasis'] = { fg = colors.yellow, italic = true },
	['@markup.underline'] = { fg = colors.orange },
	['@markup.heading'] = { fg = colors.magenta, bold = true },
	['@markup.raw'] = { fg = colors.yellow },
	['@markup.link.url'] = { fg = colors.yellow, italic = true },
	['@markup.link'] = { fg = colors.orange, bold = true },

	['@tag'] = { fg = colors.cyan },
	['@tag.attribute'] = { fg = colors.green },
	['@tag.delimiter'] = { fg = colors.cyan },

	-- Semantic
	['@class'] = { fg = colors.cyan },
	['@struct'] = { fg = colors.cyan },
	['@enum'] = { fg = colors.cyan },
	['@enumMember'] = { fg = colors.red },
	['@event'] = { fg = colors.cyan },
	['@interface'] = { fg = colors.cyan },
	['@modifier'] = { fg = colors.cyan },
	['@regexp'] = { fg = colors.yellow },
	['@typeParameter'] = { fg = colors.cyan },
	['@decorator'] = { fg = colors.cyan },

	-- -- LSP Semantic (0.9+)
	['@lsp.type.class'] = { fg = colors.cyan },
	['@lsp.type.enum'] = { fg = colors.cyan },
	['@lsp.type.decorator'] = { fg = colors.green },
	['@lsp.type.enumMember'] = { fg = colors.red },
	['@lsp.type.function'] = { fg = colors.green },
	['@lsp.type.interface'] = { fg = colors.cyan },
	['@lsp.type.macro'] = { fg = colors.cyan },
	['@lsp.type.method'] = { fg = colors.green },
	['@lsp.type.namespace'] = { fg = colors.orange },
	['@lsp.type.parameter'] = { fg = colors.orange },
	['@lsp.type.property'] = { fg = colors.blue },
	['@lsp.type.struct'] = { fg = colors.cyan },
	['@lsp.type.type'] = { fg = colors.azure },
	['@lsp.type.variable'] = { fg = fg },

	-- HTML
	htmlArg = { fg = colors.green },
	htmlBold = { fg = colors.yellow, bold = true },
	htmlEndTag = { fg = colors.cyan },
	htmlH1 = { fg = colors.magenta },
	htmlH2 = { fg = colors.magenta },
	htmlH3 = { fg = colors.magenta },
	htmlH4 = { fg = colors.magenta },
	htmlH5 = { fg = colors.magenta },
	htmlH6 = { fg = colors.magenta },
	htmlItalic = { fg = colors.red, italic = true },
	htmlLink = { fg = colors.red, underline = true },
	htmlSpecialChar = { fg = colors.yellow },
	htmlSpecialTagName = { fg = colors.cyan },
	htmlTag = { fg = colors.cyan },
	htmlTagN = { fg = colors.cyan },
	htmlTagName = { fg = colors.cyan },
	htmlTitle = { fg = white },

	-- Markdown
	markdownBlockquote = { fg = colors.yellow, italic = true },
	markdownBold = { fg = colors.orange, bold = true },
	markdownCode = { fg = colors.green },
	markdownCodeBlock = { fg = colors.orange },
	markdownCodeDelimiter = { fg = colors.red },
	markdownH1 = { link = 'rainbow1' },
	markdownH2 = { link = 'rainbow2' },
	markdownH3 = { link = 'rainbow3' },
	markdownH4 = { link = 'rainbow4' },
	markdownH5 = { link = 'rainbow5' },
	markdownH6 = { link = 'rainbow6' },
	markdownHeadingDelimiter = { fg = colors.red },
	markdownHeadingRule = { fg = colors.gradient[2] },
	markdownId = { fg = colors.red },
	markdownIdDeclaration = { fg = colors.cyan },
	markdownIdDelimiter = { fg = colors.red },
	markdownItalic = { fg = colors.yellow, italic = true },
	markdownLinkDelimiter = { fg = colors.red },
	markdownLinkText = { fg = colors.magenta },
	markdownListMarker = { fg = colors.cyan },
	markdownOrderedListMarker = { fg = colors.red },
	markdownRule = { fg = colors.gradient[2] },
	['@markup.heading.1.markdown'] = { link = 'rainbowcol1' },
	['@markup.heading.2.markdown'] = { link = 'rainbowcol2' },
	['@markup.heading.3.markdown'] = { link = 'rainbowcol3' },
	['@markup.heading.4.markdown'] = { link = 'rainbowcol4' },
	['@markup.heading.5.markdown'] = { link = 'rainbowcol5' },
	['@markup.heading.6.markdown'] = { link = 'rainbowcol6' },

	-- Diff
	diffAdded = { fg = colors.green },
	diffRemoved = { fg = colors.red },
	diffFileId = { fg = colors.yellow, bold = true, reverse = true },
	diffFile = { fg = colors.gradient[2] },
	diffNewFile = { fg = colors.green },
	diffOldFile = { fg = colors.red },

	debugPc = { bg = black },
	debugBreakpoint = { fg = colors.red, reverse = true },

	-- Git Signs
	GitSignsAdd = { fg = colors.green },
	GitSignsChange = { fg = colors.blue },
	GitSignsDelete = { fg = colors.red },
	GitSignsAddLn = { fg = black, bg = colors.green },
	GitSignsChangeLn = { fg = black, bg = colors.blue },
	GitSignsDeleteLn = { fg = black, bg = colors.red },
	GitSignsCurrentLineBlame = { fg = white },

	-- Telescope
	TelescopePromptBorder = { fg = colors.gradient[2] },
	TelescopeResultsBorder = { fg = colors.gradient[2] },
	TelescopePreviewBorder = { fg = colors.gradient[2] },
	TelescopeSelection = { fg = colors.gradient[5], bg = colors.gradient[2] },
	TelescopeMultiSelection = { fg = colors.red, bg = colors.gradient[2] },
	TelescopeNormal = { fg = fg, bg = nil },
	TelescopeMatching = { fg = colors.green },
	TelescopePromptPrefix = { fg = colors.colors[7] },
	TelescopeResultsDiffDelete = { fg = colors.red },
	TelescopeResultsDiffChange = { fg = colors.cyan },
	TelescopeResultsDiffAdd = { fg = colors.green },

	-- LSP
	DiagnosticError = { fg = colors.red },
	DiagnosticWarn = { fg = colors.yellow },
	DiagnosticInfo = { fg = colors.cyan },
	DiagnosticHint = { fg = colors.cyan },
	DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
	DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
	DiagnosticUnderlineInfo = { undercurl = true, sp = colors.cyan },
	DiagnosticUnderlineHint = { undercurl = true, sp = colors.cyan },
	DiagnosticSignError = { fg = colors.red },
	DiagnosticSignWarn = { fg = colors.yellow },
	DiagnosticSignInfo = { fg = colors.cyan },
	DiagnosticSignHint = { fg = colors.cyan },
	DiagnosticFloatingError = { fg = colors.red },
	DiagnosticFloatingWarn = { fg = colors.yellow },
	DiagnosticFloatingInfo = { fg = colors.cyan },
	DiagnosticFloatingHint = { fg = colors.cyan },
	DiagnosticVirtualTextError = { fg = colors.red },
	DiagnosticVirtualTextWarn = { fg = colors.yellow },
	DiagnosticVirtualTextInfo = { fg = colors.cyan },
	DiagnosticVirtualTextHint = { fg = colors.cyan },

	LspDiagnosticsDefaultError = { fg = colors.red },
	LspDiagnosticsDefaultWarning = { fg = colors.yellow },
	LspDiagnosticsDefaultInformation = { fg = colors.cyan },
	LspDiagnosticsDefaultHint = { fg = colors.cyan },
	LspDiagnosticsUnderlineError = { fg = colors.red, undercurl = true },
	LspDiagnosticsUnderlineWarning = { fg = colors.yellow, undercurl = true },
	LspDiagnosticsUnderlineInformation = { fg = colors.cyan, undercurl = true },
	LspDiagnosticsUnderlineHint = { fg = colors.cyan, undercurl = true },
	LspReferenceText = { fg = colors.orange },
	LspReferenceRead = { fg = colors.orange },
	LspReferenceWrite = { fg = colors.orange },
	LspCodeLens = { fg = colors.cyan },
	LspInlayHint = { fg = '#969696', bg = '#2f3146' },

	--LSP Saga
	LspFloatWinNormal = { fg = fg },
	LspFloatWinBorder = { fg = colors.gradient[2] },
	LspSagaHoverBorder = { fg = colors.gradient[2] },
	LspSagaSignatureHelpBorder = { fg = colors.gradient[2] },
	LspSagaCodeActionBorder = { fg = colors.gradient[2] },
	LspSagaDefPreviewBorder = { fg = colors.gradient[2] },
	LspLinesDiagBorder = { fg = colors.gradient[2] },
	LspSagaRenameBorder = { fg = colors.gradient[2] },
	LspSagaBorderTitle = { fg = black },
	LSPSagaDiagnosticTruncateLine = { fg = colors.gradient[2] },
	LspSagaDiagnosticBorder = { fg = colors.gradient[2] },
	LspSagaShTruncateLine = { fg = colors.gradient[2] },
	LspSagaDocTruncateLine = { fg = colors.gradient[2] },
	LspSagaLspFinderBorder = { fg = colors.gradient[2] },
	CodeActionNumber = { bg = 'NONE', fg = colors.cyan },

	-- IndentBlankLine
	IndentBlanklineContextChar = { fg = colors.rose, nocombine = true },

	-- Nvim compe
	CmpItemAbbrDeprecated = { fg = white, bg = muted },
	CmpItemAbbrMatch = { fg = colors.cyan, bg = muted },

	-- Compe
	CompeDocumentation = { link = 'Pmenu' },
	CompeDocumentationBorder = { link = 'Pmenu' },

	-- Cmp
	CmpItemAbbr = { fg = white, bg = muted },
	CmpItemKind = { fg = white, bg = muted },
	CmpItemKindMethod = { link = '@function.method' },
	CmpItemKindText = { link = '@markup' },
	CmpItemKindFunction = { link = '@function' },
	CmpItemKindConstructor = { link = '@type' },
	CmpItemKindVariable = { link = '@variable' },
	CmpItemKindClass = { link = '@type' },
	CmpItemKindInterface = { link = '@type' },
	CmpItemKindModule = { link = '@module' },
	CmpItemKindProperty = { link = '@property' },
	CmpItemKindOperator = { link = '@operator' },
	CmpItemKindReference = { link = '@variable.parameter.reference' },
	CmpItemKindUnit = { link = '@variable.member' },
	CmpItemKindValue = { link = '@variable.member' },
	CmpItemKindField = { link = '@variable.member' },
	CmpItemKindEnum = { link = '@variable.member' },
	CmpItemKindKeyword = { link = '@keyword' },
	CmpItemKindSnippet = { link = '@markup' },
	CmpItemKindColor = { link = 'DevIconCss' },
	CmpItemKindFile = { link = 'TSURI' },
	CmpItemKindFolder = { link = 'TSURI' },
	CmpItemKindEvent = { link = '@constant' },
	CmpItemKindEnumMember = { link = '@variable.member' },
	CmpItemKindConstant = { link = '@constant' },
	CmpItemKindStruct = { link = '@structure' },
	CmpItemKindTypeParameter = { link = '@variable.parameter' },

	-- navic
	NavicIconsFile = { link = 'CmpItemKindFile' },
	NavicIconsModule = { link = 'CmpItemKindModule' },
	NavicIconsNamespace = { link = 'CmpItemKindModule' },
	NavicIconsPackage = { link = 'CmpItemKindModule' },
	NavicIconsClass = { link = 'CmpItemKindClass' },
	NavicIconsMethod = { link = 'CmpItemKindMethod' },
	NavicIconsProperty = { link = 'CmpItemKindProperty' },
	NavicIconsField = { link = 'CmpItemKindField' },
	NavicIconsConstructor = { link = 'CmpItemKindConstructor' },
	NavicIconsEnum = { link = 'CmpItemKindEnum' },
	NavicIconsInterface = { link = 'CmpItemKindInterface' },
	NavicIconsFunction = { link = 'CmpItemKindFunction' },
	NavicIconsVariable = { link = 'CmpItemKindVariable' },
	NavicIconsConstant = { link = 'CmpItemKindConstant' },
	NavicIconsString = { link = 'String' },
	NavicIconsNumber = { link = 'Number' },
	NavicIconsBoolean = { link = 'Boolean' },
	NavicIconsArray = { link = 'CmpItemKindClass' },
	NavicIconsObject = { link = 'CmpItemKindClass' },
	NavicIconsKey = { link = 'CmpItemKindKeyword' },
	NavicIconsKeyword = { link = 'CmpItemKindKeyword' },
	NavicIconsNull = { fg = colors.blue },
	NavicIconsEnumMember = { link = 'CmpItemKindEnumMember' },
	NavicIconsStruct = { link = 'CmpItemKindStruct' },
	NavicIconsEvent = { link = 'CmpItemKindEvent' },
	NavicIconsOperator = { link = 'CmpItemKindOperator' },
	NavicIconsTypeParameter = { link = 'CmpItemKindTypeParameter' },
	NavicText = { fg = colors.gradient[2] },
	NavicSeparator = { fg = colors.gradient[2] },

	-- TS rainbow colors
	rainbowcol1 = { fg = colors.red },
	rainbowcol2 = { fg = colors.yellow },
	rainbowcol3 = { fg = colors.blue },
	rainbowcol4 = { fg = colors.orange },
	rainbowcol5 = { fg = colors.green },
	rainbowcol6 = { fg = colors.magenta },
	rainbowcol7 = { fg = colors.cyan },

	-- Rainbow delimiter
	RainbowDelimiterRed = { fg = colors.red },
	RainbowDelimiterYellow = { fg = colors.yellow },
	RainbowDelimiterBlue = { fg = colors.blue },
	RainbowDelimiterOrange = { fg = colors.orange },
	RainbowDelimiterGreen = { fg = colors.green },
	RainbowDelimiterViolet = { fg = colors.violet },
	RainbowDelimiterCyan = { fg = colors.cyan },

	-- mini.indentscope
	MiniIndentscopeSymbol = { fg = '#B5629B' },
	MiniIndentscopeSymbolOff = { fg = '#B5629B' },

	-- goolord/alpha-nvim
	AlphaHeader = { fg = colors.red },
	AlphaButtons = { fg = colors.cyan },
	AlphaShortcut = { fg = colors.orange },
	AlphaFooter = { fg = colors.red, italic = true },

	-- nvimdev/dashboard-nvim
	DashboardShortCut = { fg = colors.cyan },
	DashboardHeader = { fg = colors.red },
	DashboardCenter = { fg = fg },
	DashboardFooter = { fg = colors.red, italic = true },
	DashboardKey = { fg = colors.orange },
	DashboardDesc = { fg = colors.cyan },
	DashboardIcon = { fg = colors.cyan, bold = true },

	-- rcarriga/nvim-dap-ui
	DapUIPlayPause = { fg = colors.spring_green },
	DapUIRestart = { fg = colors.green },
	DapUIStop = { fg = colors.red },
	DapUIStepOver = { fg = colors.cyan },
	DapUIStepInto = { fg = colors.cyan },
	DapUIStepOut = { fg = colors.cyan },
	DapUIStepBack = { fg = colors.cyan },
	DapUIType = { fg = colors.blue },
	DapUIScope = { fg = colors.azure },
	DapUIModifiedValue = { fg = colors.azure, bold = true },
	DapUIDecoration = { fg = colors.azure },
	DapUIThread = { fg = colors.spring_green },
	DapUIStoppedThread = { fg = colors.azure },
	DapUISource = { fg = colors.blue },
	DapUILineNumber = { fg = colors.azure },
	DapUIFloatBorder = { fg = colors.azure },
	DapUIWatchesEmpty = { fg = colors.magenta },
	DapUIWatchesValue = { fg = colors.spring_green },
	DapUIWatchesError = { fg = colors.magenta },
	DapUIBreakpointsPath = { fg = colors.azure },
	DapUIBreakpointsInfo = { fg = colors.spring_green },
	DapUIBreakpointsCurrentLine = { fg = colors.spring_green, bold = true },
	DapStoppedLine = { default = true, link = 'Visual' },
	DapUIWinSelect = { fg = colors.azure, bold = true },
}

for group, setting in pairs(groups) do
	vim.api.nvim_set_hl(0, group, setting)
end

-- local groups = {
-- 	Normal = { fg = colors.fg, bg = colors.bg },
-- 	NormalFloat = { fg = colors.fg, bg = colors.bg },
-- 	Comment = { fg = colors.comment, italic = true },
-- 	Constant = { fg = colors.yellow },
-- 	String = { fg = colors.yellow },
-- 	Character = { fg = colors.green },
-- 	Number = { fg = colors.orange },
-- 	Boolean = { fg = colors.cyan },
-- 	Float = { fg = colors.orange },
-- 	FloatBorder = { fg = colors.white },
-- 	Operator = { fg = colors.purple },
-- 	Keyword = { fg = colors.cyan },
-- 	Keywords = { fg = colors.cyan },
-- 	Identifier = { fg = colors.cyan },
-- 	Function = { fg = colors.yellow },
-- 	Statement = { fg = colors.purple },
-- 	Conditional = { fg = colors.pink },
-- 	Repeat = { fg = colors.pink },
-- 	Label = { fg = colors.cyan },
-- 	Exception = { fg = colors.purple },
-- 	PreProc = { fg = colors.yellow },
-- 	Include = { fg = colors.purple },
-- 	Define = { fg = colors.purple },
-- 	Title = { fg = colors.cyan },
-- 	Macro = { fg = colors.purple },
-- 	PreCondit = { fg = colors.cyan },
-- 	Type = { fg = colors.cyan },
-- 	StorageClass = { fg = colors.pink },
-- 	Structure = { fg = colors.yellow },
-- 	TypeDef = { fg = colors.yellow },
-- 	Special = { fg = colors.green, italic = true },
-- 	SpecialComment = { fg = colors.comment, italic = true },
-- 	Error = { fg = colors.bright_red },
-- 	Todo = { fg = colors.purple, bold = true, italic = true },
-- 	Underlined = { fg = colors.cyan, underline = true },
--
-- 	Cursor = { reverse = true },
-- 	CursorLineNr = { fg = colors.fg, bold = true },
--
-- 	SignColumn = { bg = colors.bg },
--
-- 	Conceal = { fg = colors.comment },
-- 	CursorColumn = { bg = colors.black },
-- 	CursorLine = { bg = colors.selection },
-- 	ColorColumn = { bg = colors.selection },
--
-- 	StatusLine = { fg = colors.white, bg = colors.black },
-- 	StatusLineNC = { fg = colors.comment },
-- 	StatusLineTerm = { fg = colors.white, bg = colors.black },
-- 	StatusLineTermNC = { fg = colors.comment },
--
-- 	Directory = { fg = colors.cyan },
-- 	DiffAdd = { fg = colors.bg, bg = colors.green },
-- 	DiffChange = { fg = colors.orange },
-- 	DiffDelete = { fg = colors.red },
-- 	DiffText = { fg = colors.comment },
--
-- 	ErrorMsg = { fg = colors.bright_red },
-- 	VertSplit = { fg = colors.black },
-- 	WinSeparator = { fg = colors.purple },
-- 	Folded = { fg = colors.comment },
-- 	FoldColumn = {},
-- 	Search = { fg = colors.black, bg = colors.orange },
-- 	IncSearch = { fg = colors.orange, bg = colors.comment },
-- 	LineNr = { fg = colors.comment },
-- 	MatchParen = { fg = colors.fg, underline = true },
-- 	NonText = { fg = colors.nontext },
-- 	Pmenu = { fg = colors.white, bg = colors.menu },
-- 	PmenuSel = { fg = colors.white, bg = colors.selection },
-- 	PmenuSbar = { bg = colors.bg },
-- 	PmenuThumb = { bg = colors.selection },
--
-- 	Question = { fg = colors.purple },
-- 	QuickFixLine = { fg = colors.black, bg = colors.yellow },
-- 	SpecialKey = { fg = colors.nontext },
--
-- 	SpellBad = { fg = colors.bright_red, underline = true },
-- 	SpellCap = { fg = colors.yellow },
-- 	SpellLocal = { fg = colors.yellow },
-- 	SpellRare = { fg = colors.yellow },
--
-- 	TabLine = { fg = colors.comment },
-- 	TabLineSel = { fg = colors.white },
-- 	TabLineFill = { bg = colors.bg },
-- 	Terminal = { fg = colors.white, bg = colors.black },
-- 	Visual = { bg = colors.visual },
-- 	VisualNOS = { fg = colors.visual },
-- 	WarningMsg = { fg = colors.yellow },
-- 	WildMenu = { fg = colors.black, bg = colors.white },
--
-- 	EndOfBuffer = { fg = colors.bg },
--
-- 	-- TreeSitter
-- 	['@error'] = { fg = colors.bright_red },
-- 	['@punctuation.delimiter'] = { fg = colors.fg },
-- 	['@punctuation.bracket'] = { fg = colors.fg },
-- 	['@markup.list'] = { fg = colors.cyan },
--
-- 	['@constant'] = { fg = colors.purple },
-- 	['@constant.builtin'] = { fg = colors.purple },
-- 	['@markup.link.label.symbol'] = { fg = colors.purple },
--
-- 	['@constant.macro'] = { fg = colors.cyan },
-- 	['@string.regexp'] = { fg = colors.red },
-- 	['@string'] = { fg = colors.yellow },
-- 	['@string.escape'] = { fg = colors.cyan },
-- 	['@string.special.symbol'] = { fg = colors.purple },
-- 	['@character'] = { fg = colors.green },
-- 	['@number'] = { fg = colors.purple },
-- 	['@boolean'] = { fg = colors.purple },
-- 	['@number.float'] = { fg = colors.green },
-- 	['@annotation'] = { fg = colors.yellow },
-- 	['@attribute'] = { fg = colors.cyan },
-- 	['@module'] = { fg = colors.orange },
--
-- 	['@function.builtin'] = { fg = colors.cyan },
-- 	['@function'] = { fg = colors.green },
-- 	['@function.macro'] = { fg = colors.green },
-- 	['@variable.parameter'] = { fg = colors.orange },
-- 	['@variable.parameter.reference'] = { fg = colors.orange },
-- 	['@function.method'] = { fg = colors.green },
-- 	['@variable.member'] = { fg = colors.orange },
-- 	['@property'] = { fg = colors.purple },
-- 	['@constructor'] = { fg = colors.cyan },
--
-- 	['@keyword.conditional'] = { fg = colors.pink },
-- 	['@keyword.repeat'] = { fg = colors.pink },
-- 	['@label'] = { fg = colors.cyan },
--
-- 	['@keyword'] = { fg = colors.pink },
-- 	['@keyword.function'] = { fg = colors.cyan },
-- 	['@keyword.function.ruby'] = { fg = colors.pink },
-- 	['@keyword.operator'] = { fg = colors.pink },
-- 	['@operator'] = { fg = colors.pink },
-- 	['@keyword.exception'] = { fg = colors.purple },
-- 	['@type'] = { fg = colors.bright_cyan },
-- 	['@type.builtin'] = { fg = colors.cyan, italic = true },
-- 	['@type.qualifier'] = { fg = colors.pink },
-- 	['@structure'] = { fg = colors.purple },
-- 	['@keyword.include'] = { fg = colors.pink },
--
-- 	['@variable'] = { fg = colors.fg },
-- 	['@variable.builtin'] = { fg = colors.purple },
--
-- 	['@markup'] = { fg = colors.orange },
-- 	['@markup.strong'] = { fg = colors.orange, bold = true }, -- bold
-- 	['@markup.emphasis'] = { fg = colors.yellow, italic = true }, -- italic
-- 	['@markup.underline'] = { fg = colors.orange },
-- 	['@markup.heading'] = { fg = colors.pink, bold = true }, -- title
-- 	['@markup.raw'] = { fg = colors.yellow }, -- inline code
-- 	['@markup.link.url'] = { fg = colors.yellow, italic = true }, -- urls
-- 	['@markup.link'] = { fg = colors.orange, bold = true },
--
-- 	['@tag'] = { fg = colors.cyan },
-- 	['@tag.attribute'] = { fg = colors.green },
-- 	['@tag.delimiter'] = { fg = colors.cyan },
--
-- 	-- Semantic
-- 	['@class'] = { fg = colors.cyan },
-- 	['@struct'] = { fg = colors.cyan },
-- 	['@enum'] = { fg = colors.cyan },
-- 	['@enumMember'] = { fg = colors.purple },
-- 	['@event'] = { fg = colors.cyan },
-- 	['@interface'] = { fg = colors.cyan },
-- 	['@modifier'] = { fg = colors.cyan },
-- 	['@regexp'] = { fg = colors.yellow },
-- 	['@typeParameter'] = { fg = colors.cyan },
-- 	['@decorator'] = { fg = colors.cyan },
--
-- 	-- LSP Semantic (0.9+)
-- 	['@lsp.type.class'] = { fg = colors.cyan },
-- 	['@lsp.type.enum'] = { fg = colors.cyan },
-- 	['@lsp.type.decorator'] = { fg = colors.green },
-- 	['@lsp.type.enumMember'] = { fg = colors.purple },
-- 	['@lsp.type.function'] = { fg = colors.green },
-- 	['@lsp.type.interface'] = { fg = colors.cyan },
-- 	['@lsp.type.macro'] = { fg = colors.cyan },
-- 	['@lsp.type.method'] = { fg = colors.green },
-- 	['@lsp.type.namespace'] = { fg = colors.orange },
-- 	['@lsp.type.parameter'] = { fg = colors.orange },
-- 	['@lsp.type.property'] = { fg = colors.purple },
-- 	['@lsp.type.struct'] = { fg = colors.cyan },
-- 	['@lsp.type.type'] = { fg = colors.bright_cyan },
-- 	['@lsp.type.variable'] = { fg = colors.fg },
--
-- 	-- HTML
-- 	htmlArg = { fg = colors.green },
-- 	htmlBold = { fg = colors.yellow, bold = true },
-- 	htmlEndTag = { fg = colors.cyan },
-- 	htmlH1 = { fg = colors.pink },
-- 	htmlH2 = { fg = colors.pink },
-- 	htmlH3 = { fg = colors.pink },
-- 	htmlH4 = { fg = colors.pink },
-- 	htmlH5 = { fg = colors.pink },
-- 	htmlH6 = { fg = colors.pink },
-- 	htmlItalic = { fg = colors.purple, italic = true },
-- 	htmlLink = { fg = colors.purple, underline = true },
-- 	htmlSpecialChar = { fg = colors.yellow },
-- 	htmlSpecialTagName = { fg = colors.cyan },
-- 	htmlTag = { fg = colors.cyan },
-- 	htmlTagN = { fg = colors.cyan },
-- 	htmlTagName = { fg = colors.cyan },
-- 	htmlTitle = { fg = colors.white },
--
-- 	-- Markdown
-- 	markdownBlockquote = { fg = colors.yellow, italic = true },
-- 	markdownBold = { fg = colors.orange, bold = true },
-- 	markdownCode = { fg = colors.green },
-- 	markdownCodeBlock = { fg = colors.orange },
-- 	markdownCodeDelimiter = { fg = colors.red },
-- 	markdownH1 = { link = 'rainbow1' },
-- 	markdownH2 = { link = 'rainbow2' },
-- 	markdownH3 = { link = 'rainbow3' },
-- 	markdownH4 = { link = 'rainbow4' },
-- 	markdownH5 = { link = 'rainbow5' },
-- 	markdownH6 = { link = 'rainbow6' },
-- 	markdownHeadingDelimiter = { fg = colors.red },
-- 	markdownHeadingRule = { fg = colors.comment },
-- 	markdownId = { fg = colors.purple },
-- 	markdownIdDeclaration = { fg = colors.cyan },
-- 	markdownIdDelimiter = { fg = colors.purple },
-- 	markdownItalic = { fg = colors.yellow, italic = true },
-- 	markdownLinkDelimiter = { fg = colors.purple },
-- 	markdownLinkText = { fg = colors.pink },
-- 	markdownListMarker = { fg = colors.cyan },
-- 	markdownOrderedListMarker = { fg = colors.red },
-- 	markdownRule = { fg = colors.comment },
-- 	['@markup.heading.1.markdown'] = { link = 'rainbowcol1' },
-- 	['@markup.heading.2.markdown'] = { link = 'rainbowcol2' },
-- 	['@markup.heading.3.markdown'] = { link = 'rainbowcol3' },
-- 	['@markup.heading.4.markdown'] = { link = 'rainbowcol4' },
-- 	['@markup.heading.5.markdown'] = { link = 'rainbowcol5' },
-- 	['@markup.heading.6.markdown'] = { link = 'rainbowcol6' },
--
-- 	--  Diff
-- 	diffAdded = { fg = colors.green },
-- 	diffRemoved = { fg = colors.red },
-- 	diffFileId = { fg = colors.yellow, bold = true, reverse = true },
-- 	diffFile = { fg = colors.nontext },
-- 	diffNewFile = { fg = colors.green },
-- 	diffOldFile = { fg = colors.red },
--
-- 	debugPc = { bg = colors.menu },
-- 	debugBreakpoint = { fg = colors.red, reverse = true },
--
-- 	-- Git Signs
-- 	GitSignsAdd = { fg = colors.bright_green },
-- 	GitSignsChange = { fg = colors.cyan },
-- 	GitSignsDelete = { fg = colors.bright_red },
-- 	GitSignsAddLn = { fg = colors.black, bg = colors.bright_green },
-- 	GitSignsChangeLn = { fg = colors.black, bg = colors.cyan },
-- 	GitSignsDeleteLn = { fg = colors.black, bg = colors.bright_red },
-- 	GitSignsCurrentLineBlame = { fg = colors.white },
--
-- 	-- Telescope
-- 	TelescopePromptBorder = { fg = colors.comment },
-- 	TelescopeResultsBorder = { fg = colors.comment },
-- 	TelescopePreviewBorder = { fg = colors.comment },
-- 	TelescopeSelection = { fg = colors.white, bg = colors.selection },
-- 	TelescopeMultiSelection = { fg = colors.purple, bg = colors.selection },
-- 	TelescopeNormal = { fg = colors.fg, bg = colors.bg },
-- 	TelescopeMatching = { fg = colors.green },
-- 	TelescopePromptPrefix = { fg = colors.purple },
-- 	TelescopeResultsDiffDelete = { fg = colors.red },
-- 	TelescopeResultsDiffChange = { fg = colors.cyan },
-- 	TelescopeResultsDiffAdd = { fg = colors.green },
--
-- 	-- -- Flash
-- 	-- FlashLabel = { bg = colors.red, fg = colors.bright_white },
--
-- 	-- LSP
-- 	DiagnosticError = { fg = colors.red },
-- 	DiagnosticWarn = { fg = colors.yellow },
-- 	DiagnosticInfo = { fg = colors.cyan },
-- 	DiagnosticHint = { fg = colors.cyan },
-- 	DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
-- 	DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
-- 	DiagnosticUnderlineInfo = { undercurl = true, sp = colors.cyan },
-- 	DiagnosticUnderlineHint = { undercurl = true, sp = colors.cyan },
-- 	DiagnosticSignError = { fg = colors.red },
-- 	DiagnosticSignWarn = { fg = colors.yellow },
-- 	DiagnosticSignInfo = { fg = colors.cyan },
-- 	DiagnosticSignHint = { fg = colors.cyan },
-- 	DiagnosticFloatingError = { fg = colors.red },
-- 	DiagnosticFloatingWarn = { fg = colors.yellow },
-- 	DiagnosticFloatingInfo = { fg = colors.cyan },
-- 	DiagnosticFloatingHint = { fg = colors.cyan },
-- 	DiagnosticVirtualTextError = { fg = colors.red },
-- 	DiagnosticVirtualTextWarn = { fg = colors.yellow },
-- 	DiagnosticVirtualTextInfo = { fg = colors.cyan },
-- 	DiagnosticVirtualTextHint = { fg = colors.cyan },
--
-- 	LspDiagnosticsDefaultError = { fg = colors.red },
-- 	LspDiagnosticsDefaultWarning = { fg = colors.yellow },
-- 	LspDiagnosticsDefaultInformation = { fg = colors.cyan },
-- 	LspDiagnosticsDefaultHint = { fg = colors.cyan },
-- 	LspDiagnosticsUnderlineError = { fg = colors.red, undercurl = true },
-- 	LspDiagnosticsUnderlineWarning = { fg = colors.yellow, undercurl = true },
-- 	LspDiagnosticsUnderlineInformation = { fg = colors.cyan, undercurl = true },
-- 	LspDiagnosticsUnderlineHint = { fg = colors.cyan, undercurl = true },
-- 	LspReferenceText = { fg = colors.orange },
-- 	LspReferenceRead = { fg = colors.orange },
-- 	LspReferenceWrite = { fg = colors.orange },
-- 	LspCodeLens = { fg = colors.cyan },
-- 	LspInlayHint = { fg = '#969696', bg = '#2f3146' },
--
-- 	--LSP Saga
-- 	LspFloatWinNormal = { fg = colors.fg },
-- 	LspFloatWinBorder = { fg = colors.comment },
-- 	LspSagaHoverBorder = { fg = colors.comment },
-- 	LspSagaSignatureHelpBorder = { fg = colors.comment },
-- 	LspSagaCodeActionBorder = { fg = colors.comment },
-- 	LspSagaDefPreviewBorder = { fg = colors.comment },
-- 	LspLinesDiagBorder = { fg = colors.comment },
-- 	LspSagaRenameBorder = { fg = colors.comment },
-- 	LspSagaBorderTitle = { fg = colors.menu },
-- 	LSPSagaDiagnosticTruncateLine = { fg = colors.comment },
-- 	LspSagaDiagnosticBorder = { fg = colors.comment },
-- 	LspSagaShTruncateLine = { fg = colors.comment },
-- 	LspSagaDocTruncateLine = { fg = colors.comment },
-- 	LspSagaLspFinderBorder = { fg = colors.comment },
-- 	CodeActionNumber = { bg = 'NONE', fg = colors.cyan },
--
-- 	-- IndentBlankLine
-- 	IndentBlanklineContextChar = { fg = colors.bright_red, nocombine = true },
--
-- 	-- Nvim compe
-- 	CmpItemAbbrDeprecated = { fg = colors.white, bg = colors.bg },
-- 	CmpItemAbbrMatch = { fg = colors.cyan, bg = colors.bg },
--
-- 	-- Compe
-- 	CompeDocumentation = { link = 'Pmenu' },
-- 	CompeDocumentationBorder = { link = 'Pmenu' },
--
-- 	-- Cmp
-- 	CmpItemAbbr = { fg = colors.white, bg = colors.bg },
-- 	CmpItemKind = { fg = colors.white, bg = colors.bg },
-- 	CmpItemKindMethod = { link = '@function.method' },
-- 	CmpItemKindText = { link = '@markup' },
-- 	CmpItemKindFunction = { link = '@function' },
-- 	CmpItemKindConstructor = { link = '@type' },
-- 	CmpItemKindVariable = { link = '@variable' },
-- 	CmpItemKindClass = { link = '@type' },
-- 	CmpItemKindInterface = { link = '@type' },
-- 	CmpItemKindModule = { link = '@module' },
-- 	CmpItemKindProperty = { link = '@property' },
-- 	CmpItemKindOperator = { link = '@operator' },
-- 	CmpItemKindReference = { link = '@variable.parameter.reference' },
-- 	CmpItemKindUnit = { link = '@variable.member' },
-- 	CmpItemKindValue = { link = '@variable.member' },
-- 	CmpItemKindField = { link = '@variable.member' },
-- 	CmpItemKindEnum = { link = '@variable.member' },
-- 	CmpItemKindKeyword = { link = '@keyword' },
-- 	CmpItemKindSnippet = { link = '@markup' },
-- 	CmpItemKindColor = { link = 'DevIconCss' },
-- 	CmpItemKindFile = { link = 'TSURI' },
-- 	CmpItemKindFolder = { link = 'TSURI' },
-- 	CmpItemKindEvent = { link = '@constant' },
-- 	CmpItemKindEnumMember = { link = '@variable.member' },
-- 	CmpItemKindConstant = { link = '@constant' },
-- 	CmpItemKindStruct = { link = '@structure' },
-- 	CmpItemKindTypeParameter = { link = '@variable.parameter' },
--
-- 	-- navic
-- 	NavicIconsFile = { link = 'CmpItemKindFile' },
-- 	NavicIconsModule = { link = 'CmpItemKindModule' },
-- 	NavicIconsNamespace = { link = 'CmpItemKindModule' },
-- 	NavicIconsPackage = { link = 'CmpItemKindModule' },
-- 	NavicIconsClass = { link = 'CmpItemKindClass' },
-- 	NavicIconsMethod = { link = 'CmpItemKindMethod' },
-- 	NavicIconsProperty = { link = 'CmpItemKindProperty' },
-- 	NavicIconsField = { link = 'CmpItemKindField' },
-- 	NavicIconsConstructor = { link = 'CmpItemKindConstructor' },
-- 	NavicIconsEnum = { link = 'CmpItemKindEnum' },
-- 	NavicIconsInterface = { link = 'CmpItemKindInterface' },
-- 	NavicIconsFunction = { link = 'CmpItemKindFunction' },
-- 	NavicIconsVariable = { link = 'CmpItemKindVariable' },
-- 	NavicIconsConstant = { link = 'CmpItemKindConstant' },
-- 	NavicIconsString = { link = 'String' },
-- 	NavicIconsNumber = { link = 'Number' },
-- 	NavicIconsBoolean = { link = 'Boolean' },
-- 	NavicIconsArray = { link = 'CmpItemKindClass' },
-- 	NavicIconsObject = { link = 'CmpItemKindClass' },
-- 	NavicIconsKey = { link = 'CmpItemKindKeyword' },
-- 	NavicIconsKeyword = { link = 'CmpItemKindKeyword' },
-- 	NavicIconsNull = { fg = 'blue' },
-- 	NavicIconsEnumMember = { link = 'CmpItemKindEnumMember' },
-- 	NavicIconsStruct = { link = 'CmpItemKindStruct' },
-- 	NavicIconsEvent = { link = 'CmpItemKindEvent' },
-- 	NavicIconsOperator = { link = 'CmpItemKindOperator' },
-- 	NavicIconsTypeParameter = { link = 'CmpItemKindTypeParameter' },
-- 	NavicText = { fg = 'gray' },
-- 	NavicSeparator = { fg = 'gray' },
--
-- 	-- TS rainbow colors
-- 	rainbowcol1 = { fg = colors.red },
-- 	rainbowcol2 = { fg = colors.yellow },
-- 	rainbowcol3 = { fg = colors.purple },
-- 	rainbowcol4 = { fg = colors.orange },
-- 	rainbowcol5 = { fg = colors.green },
-- 	rainbowcol6 = { fg = colors.pink },
-- 	rainbowcol7 = { fg = colors.cyan },
--
-- 	-- Rainbow delimiter
-- 	RainbowDelimiterRed = { fg = colors.red },
-- 	RainbowDelimiterYellow = { fg = colors.yellow },
-- 	RainbowDelimiterBlue = { fg = colors.purple },
-- 	RainbowDelimiterOrange = { fg = colors.orange },
-- 	RainbowDelimiterGreen = { fg = colors.green },
-- 	RainbowDelimiterViolet = { fg = colors.pink },
-- 	RainbowDelimiterCyan = { fg = colors.cyan },
--
-- 	-- mini.indentscope
-- 	MiniIndentscopeSymbol = { fg = '#B5629B' },
-- 	MiniIndentscopeSymbolOff = { fg = '#B5629B' },
--
-- 	-- goolord/alpha-nvim
-- 	AlphaHeader = { fg = colors.purple },
-- 	AlphaButtons = { fg = colors.cyan },
-- 	AlphaShortcut = { fg = colors.orange },
-- 	AlphaFooter = { fg = colors.purple, italic = true },
--
-- 	-- nvimdev/dashboard-nvim
-- 	DashboardShortCut = { fg = colors.cyan },
-- 	DashboardHeader = { fg = colors.purple },
-- 	DashboardCenter = { fg = colors.fg },
-- 	DashboardFooter = { fg = colors.purple, italic = true },
-- 	DashboardKey = { fg = colors.orange },
-- 	DashboardDesc = { fg = colors.cyan },
-- 	DashboardIcon = { fg = colors.cyan, bold = true },
--
-- 	-- rcarriga/nvim-dap-ui (UI for mfussenegger/nvim-dap)
-- 	DapUIPlayPause = { fg = colors.bright_green },
-- 	DapUIRestart = { fg = colors.green },
-- 	DapUIStop = { fg = colors.red },
-- 	DapUIStepOver = { fg = colors.cyan },
-- 	DapUIStepInto = { fg = colors.cyan },
-- 	DapUIStepOut = { fg = colors.cyan },
-- 	DapUIStepBack = { fg = colors.cyan },
-- 	DapUIType = { fg = colors.bright_blue },
-- 	DapUIScope = { fg = colors.bright_cyan },
-- 	DapUIModifiedValue = { fg = colors.bright_cyan, bold = true },
-- 	DapUIDecoration = { fg = colors.bright_cyan },
-- 	DapUIThread = { fg = colors.bright_green },
-- 	DapUIStoppedThread = { fg = colors.bright_cyan },
-- 	DapUISource = { fg = colors.bright_blue },
-- 	DapUILineNumber = { fg = colors.bright_cyan },
-- 	DapUIFloatBorder = { fg = colors.bright_cyan },
-- 	DapUIWatchesEmpty = { fg = colors.pink },
-- 	DapUIWatchesValue = { fg = colors.bright_green },
-- 	DapUIWatchesError = { fg = colors.pink },
-- 	DapUIBreakpointsPath = { fg = colors.bright_cyan },
-- 	DapUIBreakpointsInfo = { fg = colors.bright_green },
-- 	DapUIBreakpointsCurrentLine = { fg = colors.bright_green, bold = true },
-- 	DapStoppedLine = { default = true, link = 'Visual' },
-- 	DapUIWinSelect = { fg = colors.bright_cyan, bold = true },
-- }
